export const data = [
    {
        id:1,
        album:"Thriller",
        name: "Michael Jackson",
        image:"https://avatars.yandex.net/get-music-content/32236/2875792e.a.67415-1/m1000x1000",
        source: <a href="https://music.yandex.ru/album/67415" target="_blank">Послушать</a>,
        description: "Американский певец, автор песен, музыкальный продюсер, аранжировщик, танцор, хореограф, актёр, сценарист, филантроп и предприниматель. Один из самых успешных исполнителей в истории поп-музыки, известен как «Король поп-музыки», обладатель 15 премий «Грэмми» и сотен других премий.",
    },
    {
        id:2,
        album:"Divide",
        name: "Ed Sheeran",
        image:"https://avatars.yandex.net/get-music-content/28589/a96b02bd.a.4172931-7/m1000x1000",
        source: <a href= "https://music.yandex.ru/album/4172931" target="_blank">Послушать</a>,
        description: "Английский певец, автор песен, музыкант, звукозаписывающий продюсер, актёр и бизнесмен. Первый коммерческий успех пришёл к нему в июне 2011 года благодаря синглу «The A Team», занявшему третье место в британском чарте.",
    },
    {
        id:3,
        album:"A Night At The Opera",
        name: "Queen",
        image:"https://avatars.yandex.net/get-music-content/41288/ef460cde.a.215688-1/m1000x1000",
        source: <a href ="https://music.yandex.ru/album/215688"target="_blank">Послушать</a>,
        description: "Британская рок-группа, добившаяся широчайшей известности в середине 1970-х годов, и одна из наиболее успешных групп в истории рок-музыки. Средства массовой информации называют группу «культовой» и пишут, что она и по сей день имеет сотни миллионов поклонников.",
    },
    {
        id:4,
        album:"After Hours",
        name: "The Weeknd",
        image:"https://avatars.yandex.net/get-music-content/2810397/2392f211.a.10327453-1/m1000x1000",
        source: <a href="https://music.yandex.ru/album/10327453" target="_blank">Послушать</a>,
        description: "Канадский певец, автор песен и музыкальный продюсер эфиопского происхождения. В конце 2010 года Тесфайе анонимно загрузил несколько песен на YouTube под именем «The Weeknd». На протяжении 2011 года он выпустил три микстейпа по 9 песен в каждом: House of Balloons, Thursday и Echoes of Silence, которые были одобрены критиками.",
    },
    {
        id:5,
        album:"Evolve",
        name: "Imagine Dragons",
        image:"https://avatars.yandex.net/get-music-content/98892/a6be0789.a.5568718-1/m1000x1000",
        source: <a href="https://music.yandex.ru/album/5568718"target="_blank">Послушать</a>,
        description: "Американская инди-рок-группа, образованная в 2008 году в городе Лас-Вегас, США. Стали известны после выпуска дебютного студийного альбома Night Visions в сентябре 2012 года. Американский журнал Billboard назвал их самыми яркими новыми звёздами 2013 года и самой большой группой 2017 года.",
    },
    {
        id:6,
        album:"Happiness",
        name: "Hurts",
        image:"https://avatars.yandex.net/get-music-content/2357076/abbc1361.a.305374-2/m1000x1000",
        source: <a href="https://music.yandex.ru/album/305374"target="_blank">Послушать</a>,
        description: "Британский музыкальный коллектив из Манчестера, образовавшийся в 2009 году, состоящий из Тео Хатчкрафта и Адама Андерсона. Их первые два альбома, Happiness и Exile, попали в десятку лучших альбомов в Великобритании, Германии, Австрии, Швейцарии, Польше и Финляндии.",
    },
    {
        id:7,
        album:"American Idiot",
        name: "Green Day",
        image: "https://avatars.yandex.net/get-music-content/42108/e125aaa0.a.21853-1/m1000x1000",
        source: <a href="https://music.yandex.ru/album/21853"target="_blank">Послушать</a>,
        description: "Американская панк-рок группа, основанная в 1987 году. Состоит из трёх участников: Билли Джо Армстронга, Майка Дёрнта и Тре Кула. Green Day первоначально были частью панк-рок среды, сформировавшейся вокруг панк-клуба 924 Gilman Street.",
    },
    {
        id:8,
        album:"Loose",
        name: "Nelly Furtado",
        image:"https://avatars.yandex.net/get-music-content/4384958/f42fa0ce.a.15934728-1/m1000x1000",
        source: <a href="https://music.yandex.ru/album/15934728"target="_blank">Послушать</a>,
        description: "Канадская певица, автор песен, музыкальный продюсер и актриса. Её пластинки и синглы разошлись по миру общим тиражом свыше 40 млн экземпляров.",
    }
]